### ISSUE TITLE
Make the screenshot delay timer configurable for each page

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/visual.regresso#3]
The timer currently is hard-coded to 500ms. https://github.com/eaudeweb/visual.regresso/blob/master/visual.regresso.starterkit/scripts/preScreenshot.example.js#L14 and must be configurable from `config.yml` with a variable called `screenshot_timeout` globally, default to 1000 and overridable per page with another value. See example below

```
compare:
  # Output dir, absolute or relative to current dir
  output: shots
  screen_size:
    - "1300x3000"
  screenshot_timer: 1000
  # Prod and test site URLs
  url:
    prod: https://www.worldheritageoutlook.iucn.org
    test: https://iucn-who.edw.ro
  # Pages to be compared
  links:
    explore_sites: /explore-sites
    homepage:
      path: /
      screen_size:
        - "1280x1024"
      screenshot_timer: 2000
```
